In [13]:
import scipy
import scipy.io
from scipy import signal
import numpy as np
import matplotlib.pyplot as plt
from scipy.io import savemat
import os
from feature_extraction import features_estimation
import pandas as pd

In [21]:
emptyTable = scipy.io.loadmat("E:\Chris\putEMG Project\Data\emptyTable.mat")
print("This is a gesture type")
newTable = emptyTable["table"]
newTable = np.array(newTable)

This is a gesture type


In [ ]:
print(newTable[0].shape)
print(f"{newTable[0][0]=}")

(7,)
newTable[0][0]=array([[array([[0]], dtype=uint8), array([[0]], dtype=uint8),
        array([[0]], dtype=uint8), array([[0]], dtype=uint8),
        array([[0]], dtype=uint8), array([[0]], dtype=uint8),
        array([[0]], dtype=uint8), array([[0]], dtype=uint8),
        array([[0]], dtype=uint8), array([[0]], dtype=uint8),
        array([[0]], dtype=uint8), array([[0]], dtype=uint8),
        array([[0]], dtype=uint8), array([[0]], dtype=uint8),
        array([[0]], dtype=uint8), array([[0]], dtype=uint8),
        array([[0]], dtype=uint8), array([[0]], dtype=uint8),
        array([[0]], dtype=uint8), array([[0]], dtype=uint8),
        array([[0]], dtype=uint8), array([[0]], dtype=uint8),
        array([[0]], dtype=uint8), array([[0]], dtype=uint8)],
       [array([[0]], dtype=uint8), array([[0]], dtype=uint8),
        array([[0]], dtype=uint8), array([[0]], dtype=uint8),
        array([[0]], dtype=uint8), array([[0]], dtype=uint8),
        array([[0]], dtype=uint8), array([[0]], d

In [ ]:
def extract_features(file_path, sub_num, sampling_rate, window_size, step_size):

    # Load the MATLAB file
    mat_data = scipy.io.loadmat(file_path)
    data = mat_data["processed_data"]
    set_of_all_gesture_by_subject = np.array(data)

    gestures = set_of_all_gesture_by_subject.shape[1]
    repetitions = set_of_all_gesture_by_subject.shape[0]
    sensors = (set_of_all_gesture_by_subject[0][0].shape)[1]

    features_for_gesture_type = []


    # all gestures types
    for i in range(gestures):

        features_for_repetition = []

        # all repetitions of a specific type
        for j in range(repetitions): # shape (28,)

            features_for_signal = []

            # all channels 
            for k in range(sensors):

                # feature Extraction
                
                emg_features, features_names = features_estimation(set_of_all_gesture_by_subject[j][i][:,k],  "Gesture " + str(i+1) + " repetition " + str(j+1) + " channel " + str(k+1)  , sampling_rate, window_size, step_size)
                emg_features = emg_features.to_numpy()
                print(emg_features.shape)                
                
                features_for_signal.append(emg_features[:,0].tolist())
                print(len(features_for_signal))    

            features_for_repetition.append(features_for_signal) 

        features_for_gesture_type.append(features_for_repetition)




    
    output_dir = "E:\\Chris\\putEMG Project\\extracted_features"
    os.makedirs(output_dir, exist_ok=True)  # Create the directory if it doesn't exist

    output_path = os.path.join(output_dir, 'extracted_features_subject'+ str(sub_num)+ '.mat')
    output_data = {'features': features_for_gesture_type}
    
    scipy.io.savemat(output_path, output_data)

In [ ]:
# guide to navigate and access elements of the table




This is a gesture type
(7, 1)
This is a repetition
(28, 1)
This is a gesture
(18, 24)
[[array([[0]], dtype=uint8) array([[0]], dtype=uint8)
  array([[0]], dtype=uint8) array([[0]], dtype=uint8)
  array([[0]], dtype=uint8) array([[0]], dtype=uint8)
  array([[0]], dtype=uint8) array([[0]], dtype=uint8)
  array([[0]], dtype=uint8) array([[0]], dtype=uint8)
  array([[0]], dtype=uint8) array([[0]], dtype=uint8)
  array([[0]], dtype=uint8) array([[0]], dtype=uint8)
  array([[0]], dtype=uint8) array([[0]], dtype=uint8)
  array([[0]], dtype=uint8) array([[0]], dtype=uint8)
  array([[0]], dtype=uint8) array([[0]], dtype=uint8)
  array([[0]], dtype=uint8) array([[0]], dtype=uint8)
  array([[0]], dtype=uint8) array([[0]], dtype=uint8)]
 [array([[0]], dtype=uint8) array([[0]], dtype=uint8)
  array([[0]], dtype=uint8) array([[0]], dtype=uint8)
  array([[0]], dtype=uint8) array([[0]], dtype=uint8)
  array([[0]], dtype=uint8) array([[0]], dtype=uint8)
  array([[0]], dtype=uint8) array([[0]], dtype=ui

In [ ]:
# access the processed data of a subject
# acces the empty table
# extract the features from the proccessed data of tha subject
# Add it to the table
# Have a table that illustrates the set of gestures that we have